# Generated by Django 3.0.6 on 2020-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200620_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='empty', max_length=100, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
