# Generated by Django 3.0.6 on 2020-06-08 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('profile_img', models.ImageField(upload_to='profile-pictures/', verbose_name='Profile Image')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('storie_img', models.ImageField(upload_to='storie-pictures/', verbose_name='Storie Imge')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Author', verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Author', verbose_name='Comment Author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story', verbose_name='Story Comment')),
            ],
        ),
    ]
