# Generated by Django 3.0.6 on 2020-07-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='stories.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_img',
            field=models.ImageField(blank=True, null=True, upload_to='recipe-pictures/', verbose_name='Recipe Image'),
        ),
    ]
