# Generated by Django 3.0.6 on 2020-06-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200620_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ManyToManyField(to='stories.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='storie_img',
            field=models.ImageField(blank=True, null=True, upload_to='storie-pictures/', verbose_name='Storie Image'),
        ),
    ]
