# Generated by Django 3.0.6 on 2020-06-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200615_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Contact Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('website', models.CharField(max_length=50, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'StaticInfo',
                'verbose_name_plural': 'StaticInfos',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tag title')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(default='empty', upload_to='category-pictures/', verbose_name='Category Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile-pictures/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=50, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='storie_img',
            field=models.ImageField(upload_to='recipe-pictures/', verbose_name='Recipe Image'),
        ),
    ]
